### ISSUE TITLE
无法设置api

### ISSUE THREAD

**Issue by Agnes4m** [XTxiaoting14332/nonebot-plugin-chatglm-plus#1]
## 错误
env里api无法读取
![image](https://github.com/XTxiaoting14332/nonebot-plugin-chatglm-plus/assets/70925546/dff4c235-8962-4428-bae0-16f0858b2cfb)

## env配置
从开放平台申请的
![image](https://github.com/XTxiaoting14332/nonebot-plugin-chatglm-plus/assets/70925546/badf5754-25eb-4d48-8d58-5cedcde1b2c2)

## 环境
python  3.10.6
ubuntu  22.04
nonebot  2.2.1
[nonebot-plugin-chatglm-plus](https://github.com/XTxiaoting14332/nonebot-plugin-chatglm-plus)  0.1.4

**Comment by XTxiaoting14332** [comment]
提供一下报错截图

**Comment by XTxiaoting14332** [comment]
将.env的``glm_api``改为``glm_api_key``
我README.md部分打错了，谢谢反馈

**Comment by XTxiaoting14332** [comment]
已修正``README.md``上的错误
