### ISSUE TITLE
不能提交pr

### ISSUE THREAD

**Issue by Cherryluoying** [XTxiaoting14332/nonebot-plugin-chatglm-plus#8]
不能提交pr，我已经修复了UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 250: invalid start byte

**Comment by XTxiaoting14332** [comment]
怎么个不能提交法（）

**Comment by Cherryluoying** [comment]
![Uploading Screenshot_2024-06-22-22-52-16-11_4d38fce200f96aeac5e860e739312e76.jpg…]()

**Comment by Cherryluoying** [comment]
按钮都不能选择

**Comment by Cherryluoying** [comment]
又修了一下乱码

**Comment by XTxiaoting14332** [comment]
你怎么在项目根目录也加了一个init.py(

**Comment by Cherryluoying** [comment]
啊？应该是第一次提交错了😱😱

**Comment by Cherryluoying** [comment]
大佬能加一下联系方式吗

**Comment by XTxiaoting14332** [comment]
> 大佬能加一下联系方式吗

qq2125714976

**Comment by SZ2528** [comment]
6
